[package]
name = "starcoin-x"
version = "0.9.1"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
structopt = "0.3.21"
anyhow = "1.0.36"
colored-diff = "0.2.2"
guppy = { version = "0.5.0", features = ["summaries"] }
indoc = "1.0.3"
toml = "0.5.8"
env_logger = "0.8.1"
log = "0.4.11"
chrono = "0.4.19"
glob = "0.3.0"
indexmap = "1.6.1"
x-core = { package="x-core", git = "https://github.com/starcoinorg/diem", rev="839ae2573a36810cd474b8095bdfb4eeb984d5d2" }
x-lint = { package="x-lint", git = "https://github.com/starcoinorg/diem", rev="839ae2573a36810cd474b8095bdfb4eeb984d5d2" }
diem-workspace-hack = { package="diem-workspace-hack", git = "https://github.com/starcoinorg/diem", rev="839ae2573a36810cd474b8095bdfb4eeb984d5d2" }
diem-x = { package="x", git = "https://github.com/starcoinorg/diem", rev="839ae2573a36810cd474b8095bdfb4eeb984d5d2" }
