apiVersion: v1
kind: Service
metadata:
  name: centauri-new-svc
  namespace: starcoin-centauri
spec:
  selector:
    app: starcoin-stress
  ports:
    -
      protocol: TCP
      port: 9840
      targetPort: 9840
      name: peer
    -
      protocol: TCP
      port: 9101
      targetPort: 9101
      name: metrics
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: starcoin-stress-new
  labels:
    app: starcoin-stress_new
    network: centauri
  namespace: starcoin-centauri
spec:
  selector:
    matchLabels:
      app: starcoin-stress-new
      network: centauri
  serviceName: centauri-new-svc
  replicas: 2
  template:
    metadata:
      name: starcoin-stress-new
      labels:
        app: starcoin-stress-new
        network: centauri
    spec:
      containers:
        - name: starcoin
          image: starcoin/starcoin:feature-stress
          imagePullPolicy: Always
          command:
            - bash
            - -c
          args:
            -
              rm -rf /sc-data/node0/centauri/starcoin.ipc /sc-data/node0/centauri/starcoindb/db/starcoindb/LOCK /sc-data/node0/centauri/account_vaults/LOCK;
              /starcoin/starcoin  -n centauri:1 --genesis-config proxima -d /sc-data/node0/ --seed $(SEED) --disable-mdns=false --rpc-address 0.0.0.0;
              ret=$?;
              if [ $ret -ne 0 ]; then
              echo "Node start fail, try to remove config.";
              rm /sc-data/node0/centauri/config.toml;
              fi;
          volumeMounts:
            - name: starcoin-stress-new-volume
              mountPath: /sc-data
          env:
            - name: SEED
              valueFrom:
                configMapKeyRef:
                  name: starcoin-config
                  key: centauri_seed
        - name: starcoin1
          image: starcoin/starcoin:feature-stress
          imagePullPolicy: Always
          command:
            - bash
            - -c
          args:
            -
              rm -rf /sc-data/node1/centauri/starcoin.ipc /sc-data/node1/centauri/starcoindb/db/starcoindb/LOCK /sc-data/node1/centauri/account_vaults/LOCK;
              /starcoin/starcoin  -n centauri:1 --genesis-config proxima -d /sc-data/node1 --seed $(SEED) --disable-mdns=false --disable-http-rpc --rpc-address 0.0.0.0 --metrics-port=9102 --tcp-port=9861 --websocket-port=9871;
              ret=$?;
              if [ $ret -ne 0 ]; then
              echo "Node start fail, try to remove config.";
              rm /sc-data/node1/centauri/config.toml;
              fi;
          volumeMounts:
            - name: starcoin-stress-new-volume
              mountPath: /sc-data
        - name: starcoin2
          image: starcoin/starcoin:feature-stress
          imagePullPolicy: Always
          command:
            - bash
            - -c
          args:
            -
              rm -rf /sc-data/node2/centauri/starcoin.ipc /sc-data/node2/centauri/starcoindb/db/starcoindb/LOCK /sc-data/node2/centauri/account_vaults/LOCK;
              /starcoin/starcoin  -n centauri:1 --genesis-config proxima -d /sc-data/node2 --seed $(SEED) --disable-mdns=false --disable-http-rpc --rpc-address 0.0.0.0 --metrics-port=9103 --tcp-port=9862 --websocket-port=9872;
              ret=$?;
              if [ $ret -ne 0 ]; then
              echo "Node start fail, try to remove config.";
              rm /sc-data/node2/centauri/config.toml;
              fi;
          volumeMounts:
            - name: starcoin-stress-new-volume
              mountPath: /sc-data
          env:
            - name: SEED
              valueFrom:
                configMapKeyRef:
                  name: starcoin-config
                  key: centauri_seed
        - name: starcoin3
          image: starcoin/starcoin:feature-stress
          imagePullPolicy: Always
          command:
            - bash
            - -c
          args:
            -
              rm -rf /sc-data/node3/centauri/starcoin.ipc /sc-data/node3/centauri/starcoindb/db/starcoindb/LOCK /sc-data/node3/centauri/account_vaults/LOCK;
              /starcoin/starcoin  -n centauri:1 --genesis-config proxima -d /sc-data/node3 --seed $(SEED) --disable-mdns=false --disable-http-rpc --rpc-address 0.0.0.0 --metrics-port=9104 --tcp-port=9863 --websocket-port=9873;
              ret=$?;
              if [ $ret -ne 0 ]; then
              echo "Node start fail, try to remove config.";
              rm /sc-data/node3/centauri/config.toml;
              fi;
          volumeMounts:
            - name: starcoin-stress-new-volume
              mountPath: /sc-data
        - name: starcoin4
          image: starcoin/starcoin:feature-stress
          imagePullPolicy: Always
          command:
            - bash
            - -c
          args:
            - rm -rf /sc-data/node4/centauri/starcoin.ipc /sc-data/node4/centauri/starcoindb/db/starcoindb/LOCK /sc-data/node4/centauri/account_vaults/LOCK;
              /starcoin/starcoin  -n centauri:1 --genesis-config proxima -d /sc-data/node4 --seed $(SEED) --disable-mdns=false --disable-http-rpc --rpc-address 0.0.0.0 --metrics-port=9105 --tcp-port=9864 --websocket-port=9874;
              ret=$?;
              if [ $ret -ne 0 ]; then
              echo "Node start fail, try to remove config.";
              rm /sc-data/node4/centauri/config.toml;
              fi;
          volumeMounts:
            - name: starcoin-stress-new-volume
              mountPath: /sc-data
      nodeSelector:
        doks.digitalocean.com/node-pool: pool-stress
  volumeClaimTemplates:
    - metadata:
        name: starcoin-stress-new-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 50Gi
