apiVersion: v1
kind: Service
metadata:
  name: centauri-new-svc
  namespace: starcoin-centauri
spec:
  selector:
    app: starcoin-stress
  ports:
    -
      protocol: TCP
      port: 9840
      targetPort: 9840
      name: peer
    -
      protocol: TCP
      port: 9101
      targetPort: 9101
      name: metrics
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: starcoin-stress-new
  labels:
    app: starcoin-stress_new
    network: centauri
  namespace: starcoin-centauri
spec:
  selector:
    matchLabels:
      app: starcoin-stress-new
      network: centauri
  serviceName: centauri-new-svc
  replicas: 30
  template:
    metadata:
      name: starcoin-stress-new
      labels:
        app: starcoin-stress-new
        network: centauri
    spec:
      containers:
        - name: starcoin
          image: starcoin/starcoin:feature-stress
          imagePullPolicy: Always
          resources:
            limits:
              memory: 500Mi
              cpu: 1
          command:
            - bash
            - -c
          args:
            -
              rm -rf /sc-data/centauri/starcoin.ipc /sc-data/centauri/starcoindb/db/starcoindb/LOCK /sc-data/centauri/account_vaults/LOCK;
              /starcoin/starcoin  -n centauri:1 --genesis-config proxima -d /sc-data --seed $(SEED) --disable-mdns=false --rpc-address 0.0.0.0;
              ret=$?;
              if [ $ret -ne 0 ]; then
              echo "Node start fail, try to remove config.";
              rm /sc-data/centauri/config.toml;
              fi;
          volumeMounts:
            - name: starcoin-stress-new-volume
              mountPath: /sc-data
          env:
            - name: SEED
              valueFrom:
                configMapKeyRef:
                  name: starcoin-config
                  key: centauri_seed
      nodeSelector:
        doks.digitalocean.com/node-pool: pool-stress

  volumeClaimTemplates:
    - metadata:
        name: starcoin-stress-new-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 20Gi
