apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    serviceapp: starcoin-stress
    release:  prometheus-operator
  name: stress-servicemonitor
  namespace:  prometheus-operator
spec:
  selector:
    matchLabels:
      app: starcoin-stress_new
      release: prometheus-operator
  endpoints:
    - port: metrics
  namespaceSelector:
    matchNames:
      - starcoin-centauri
